# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "73dceb248d9c50af181395367a12b4c2"
name = "PSF Engine"
application_url = "https://dev.prepservicesfba.com"
embedded = false

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "/api/shopify/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_fulfillments,write_inventory,read_inventory,write_locations,read_locations,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://dev.prepservicesfba.com/dashboard/integrations/shopify/callback"
]
